CREATE TABLE IF NOT EXISTS products
(
    id INT PRIMARY KEY,
    name VARCHAR (250) NOT NULL,
    category VARCHAR (100) NOT NULL,
    description VARCHAR (1000)
);

CREATE SEQUENCE IF NOT EXISTS PRODUCTSSEQ START WITH 100000;

CREATE TABLE IF NOT EXISTS cart_items
(
    cartId UUID,
    productId INT,
    price DOUBLE PRECISION,
    currency VARCHAR (3),
    cartItemType VARCHAR (20)
);